### ISSUE TITLE
Switch to CrowdAnki plugin

### ISSUE THREAD

**Issue by gnarlex** [KarelZe/anki-decks#1]
+100 Karma for helping future KIT students out :1st_place_medal: 

IMO this repository has a lot of potential! Unfortunately, Anki decks are per default exported as binary *.apkg files, making it harder for other students to contribute (e.g. create pull requests for typos).

There is an Anki plugin called [CrowdAnki](https://ankiweb.net/shared/info/1788670778) which exports a deck as folder containing a JSON file and a media folder (for screenshots, etc.). You can see an example of another (KIT) Anki repo using it here: [sebimarkgraf/synopses-anki](https://github.com/sebimarkgraf/synopses-anki)

**Comment by KarelZe** [comment]
Thanks for the praise @gnarlex.

You are definitely right, having binary files makes contributions really difficult. I'll look into CrowdAnki over the next days.
Thanks for the suggestion :-)

I might just provide both:
1. The crowd-anki version for people who want to contribute / have the add-on installed
2. An automatically exported deck for people, who have no add-ins installed

Is there a specific deck, with which we should start?

Best,
Markus

**Comment by gnarlex** [comment]
Providing both the binary and the crowd-anki version might be a good idea 👍  Although having duplicate information in separate files might be prone to change drift ("Alice udpates binary, Bob updates deck.json"). In the long-term there should be some pipeline job automatically creating binaries from the JSON file in a separate folder.

There's no specific deck I need right now, but I could make a PR to show what it would look like :v:

**Comment by KarelZe** [comment]
Thanks Alex for your PR. 

I'd provide the ready-to-use `.apkg` files for studying only. Editing should definitely happen in the `.json` files.
So far I had no contributions to the `.apkg` files, so I guess it shouldn't be a problem, if this process was one-way.

I'll look into creating automatic binaries over the winter break and discuss it here with you.

Stay awesome.

Markus

**Comment by KarelZe** [comment]
We will switch to [ki](https://langfield.github.io/ki/index.html#generating-html) as tracked in #4 . 

Changes can be made in markdown files. That is, users don't need Anki or the crowd anki extension to make changes. Also, support for providing binaries is possible.
