### ISSUE TITLE
URL-encoded paths to media files may be broken

### ISSUE THREAD

**Issue by langfield** [KarelZe/anki-decks#7]
I believe https://github.com/langfield/ki/issues/66 affects these decks in their current state.

**Comment by KarelZe** [comment]
@langfield  Thanks for briniging up this issue. 

Once the issue has been resolved, I'll regenerate the markdown from my existing binaries to resolve the issue.

**Comment by langfield** [comment]
https://github.com/langfield/ki/issues/66 has been merged!

By the way, the `README` looks super nice! :100:

**Comment by KarelZe** [comment]
@langfield Thanks for fixing this issue and the feedback on the readme. Will clone the decks later. 👍

**Comment by KarelZe** [comment]
@langfield it's done now. Updated deck with faf0e6cfd7c37218835089bd3af9dc731f7867b9.
